apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HwangJerry/mlops-demo  # 실제 레포지토리로 변경
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
